import turtle

t = turtle.Turtle()
turtle.Screen().setup(400,400)
t.turtlesize(2)
t.speed(5)
t.penup()
t.goto(-100, 150)
t.pendown()
t.color("Black", "#ED2939")

t.begin_fill()
t.forward(100)
t.setheading(255)
t.forward(20)
t.setheading(180)
t.forward(90)
t.setheading(105)
t.forward(20)
t.end_fill()

t.penup()
t.setheading(0)
t.forward(100)
t.setheading(255)
t.forward(18)
t.pendown()

t.begin_fill()
t.forward(110)
t.setheading(195)
t.forward(23)
t.setheading(75)
t.forward(105)
t.setheading(21)
t.forward(24)
t.end_fill()

t.penup()
t.setheading(75)
t.forward(20)
t.setheading(0)
t.forward(18)
t.pendown()

t.begin_fill()
t.setheading(255)
t.forward(100)
t.setheading(15)
t.forward(20)
t.setheading(75)
t.forward(73)
t.setheading(120)
t.forward(25)
t.end_fill()

t.penup()
t.setheading(255)
t.forward(98)
t.pendown()

t.begin_fill()
t.circle(32)
t.end_fill()

t.penup()
t.setheading(345)
t.forward(16)
t.setheading(255)
t.pendown()

t.color("black", "white")
t.begin_fill()
t.circle(16)
t.end_fill()

t.penup()
t.setheading(165)
t.forward(16)
t.setheading(75)
t.forward(98)
t.setheading(0)
t.forward(15)
t.pendown()

t.color("black", "#ED2939")
t.begin_fill()
t.forward(24)
t.setheading(270)
t.forward(8)
t.setheading(180)
t.forward(8)
t.setheading(270)
t.forward(16)
t.setheading(180)
t.forward(8)
t.setheading(90)
t.forward(16)
t.setheading(180)
t.forward(8)
t.setheading(90)
t.forward(8)
t.end_fill()

t.penup()
t.setheading(0)
t.forward(30)
t.pendown()

t.begin_fill()
t.forward(8)
t.setheading(270)
t.forward(8)
t.setheading(0)
t.forward(8)
t.setheading(90)
t.forward(8)
t.setheading(0)
t.forward(8)
t.setheading(270)
t.forward(24)
t.setheading(180)
t.forward(8)
t.setheading(90)
t.forward(8)
t.setheading(180)
t.forward(8)
t.setheading(270)
t.forward(8)
t.setheading(180)
t.forward(8)
t.setheading(90)
t.forward(24)
t.end_fill()

t.penup()
t.setheading(180)
t.forward(70)
t.setheading(270)
t.forward(175)
t.pendown()

i = 270
while True:
    t.setheading(i)
    i = i - 5